### ISSUE TITLE
[Bug] "Cannot read property 'merge' of undefined" when starting both HTTP API server and gateway

### ISSUE THREAD

**Issue by DonaldKellett** [fosscord/fosscord#66]
I'm following [the contributing guide](https://docs.fosscord.com/contributing.html) to try to get a local Fosscord server running and when I do `npm start` in both the HTTP API server `api/` and the gateway `gateway/`, I get the following type error after attempting to connect to the local MongoDB instance:

```
TypeError: Cannot read property 'merge' of undefined
    at Object.init (/home/dsleung/fosscord/api/node_modules/@fosscord/server-util/dist/util/Config.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FosscordServer.start (/home/dsleung/fosscord/api/dist/Server.js:68:9)
```

The full output of `npm start` for the API server:

```
> @fosscord/api@1.0.0 start /home/dsleung/fosscord/api
> npm run build && node dist/start


> @fosscord/api@1.0.0 build /home/dsleung/fosscord/api
> tsc -b .

[DB] connect: mongodb://localhost:27017/fosscord?readPreference=secondaryPreferred
[DB] connected
TypeError: Cannot read property 'merge' of undefined
    at Object.init (/home/dsleung/fosscord/api/node_modules/@fosscord/server-util/dist/util/Config.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FosscordServer.start (/home/dsleung/fosscord/api/dist/Server.js:68:9)
```

And for the gateway:

```
> @fosscord/gateway@1.0.0 start /home/dsleung/fosscord/gateway
> npm run build && node dist/start.js


> @fosscord/gateway@1.0.0 build /home/dsleung/fosscord/gateway
> npx tsc -b .

[DB] connect: mongodb://localhost:27017/fosscord?readPreference=secondaryPreferred
TypeError: Cannot read property 'merge' of undefined
    at Object.init (/home/dsleung/fosscord/gateway/node_modules/@fosscord/server-util/dist/util/Config.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server.listen (/home/dsleung/fosscord/gateway/dist/Server.js:35:9) Promise {
  <rejected> TypeError: Cannot read property 'merge' of undefined
      at Object.init (/home/dsleung/fosscord/gateway/node_modules/@fosscord/server-util/dist/util/Config.js:35:37)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Server.listen (/home/dsleung/fosscord/gateway/dist/Server.js:35:9)
}
```

I've tried updating `@fosscord/server-util` to the latest version under `api/` (successfully), but to no avail - the issue still persists:

```bash
$ npm i @fosscord/server-util@1.3.25
```

***

Environment details:

- OS: CentOS 8 Stream
- Node version: 14.17.3
- `npm` version: 6.14.13

**Comment by Flam3rboy** [comment]
the latest server-util didn't push the build files

**Comment by Flam3rboy** [comment]
try it with this new version:
```
npm i  @fosscord/server-util@1.3.26
```

**Comment by Flam3rboy** [comment]
closed due to inactivity
