### ISSUE TITLE
MongoError (selfhost)

### ISSUE THREAD

**Issue by ThatOneCalculator** [fosscord/fosscord#83]
![image](https://user-images.githubusercontent.com/44733677/128810994-c1a60697-a925-43d9-bc55-e929a703bc9b.png)
```
MongoError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'
    at MessageStream.messageHandler (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at processIncomingData (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1628571804 },
  ok: 0,
  code: 14,
  codeName: 'TypeMismatch',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1628571804 },
    signature: { hash: [Binary], keyId: 0 }
  }
}
MongoError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'
    at MessageStream.messageHandler (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at processIncomingData (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1628571804 },
  ok: 0,
  code: 14,
  codeName: 'TypeMismatch',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1628571804 },
    signature: { hash: [Binary], keyId: 0 }
  }
} Promise {
  <rejected> MongoError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'
      at MessageStream.messageHandler (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:20)
      at MessageStream.emit (events.js:400:28)
      at processIncomingData (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at MessageStream.Writable.write (internal/streams/writable.js:303:10)
      at Socket.ondata (internal/streams/readable.js:726:22)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:290:12)
      at readableAddChunk (internal/streams/readable.js:265:9)
      at Socket.Readable.push (internal/streams/readable.js:204:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1628571804 },
    ok: 0,
    code: 14,
    codeName: 'TypeMismatch',
    '$clusterTime': { clusterTime: [Timestamp], signature: [Object] }
  }
}
register REDACTED@gmail.com ThatOneCalculator 
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/the1calc/fosscord_clone/scripts/setup/fosscord/api/node_modules/express/lib/response.js:267:15)
    at /home/the1calc/fosscord_clone/scripts/setup/fosscord/api/dist/routes/auth/register.js:247:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by Flam3rboy** [comment]
What system are you using, when did you pull the latest version, what were you trying to do?
Also can you send a screenshot of the /auth/register response in your browsers dev tools network tab

**Comment by ThatOneCalculator** [comment]
Sorry for the late reply.

Last pull: 3 days ago
Trying to do: run my own instance and make an account
Screenshot:
![image](https://user-images.githubusercontent.com/44733677/129267309-603d6dd6-6a6b-44ba-af02-1bf0697f7444.png)

**Comment by Flam3rboy** [comment]
can you show the request body

**Comment by ThatOneCalculator** [comment]
How do I do that?

**Comment by Flam3rboy** [comment]
click on header of the request /auth/register requst in the network dev tools
and scroll down to body

**Comment by ThatOneCalculator** [comment]
![image](https://user-images.githubusercontent.com/44733677/129268035-1dc76f09-1b37-43c5-9d0b-3b650903b8c3.png)

**Comment by Flam3rboy** [comment]
yeah we are currently reworking it

**Comment by Flam3rboy** [comment]
also we added rabbitmq for better event transmission, which needs to be setup
however I'm currently also adding support for local event transmission that uses nodejs.EventEmitter for the server bundle which doesn't need any extra dependency

**Comment by ThatOneCalculator** [comment]
Sounds good! Just LMK when that's all ready and I'll pull and try and set it up then

**Comment by Flam3rboy** [comment]
We had a major rewrite, so you can use any database you want. By default it uses sqlite (we are currently adding an option to change that).
Please checkout the [master branch](https://docs.fosscord.com/setup/#with-terminalshell) and try again
